### ISSUE TITLE
Please add semantic version tags

### ISSUE THREAD

**Issue by robnadin** [liveservices/LiveSDK-for-iOS#21]
[CocoaPods](https://github.com/CocoaPods/CocoaPods) is a tool for managing dependencies for OS X and iOS Xcode projects and provides a central repository for iOS/OS X libraries. This makes adding libraries to a project and updating them extremely easy and it will help users to resolve dependencies of the libraries they use.

However, `<LiveSDK-for-iOS>` doesn't have any version tags. Currently a pod cannot be submitted to the podspec repository referencing a specific commit - a version tag must be specified.

[Semantic version](http://semver.org) tags (instead of plain commit hashes/revisions) allow for [resolution of cross-dependencies](https://github.com/CocoaPods/Specs/wiki/Cross-dependencies-resolution-example).

In case you didn’t know this yet; you can tag the current HEAD as, for instance, version 1.0.0, like so:

```
$ git tag -a 1.0.0 -m "Tag release 1.0.0"
$ git push --tags
```

**Comment by aclev** [comment]
Fixed with PR #47
