### ISSUE TITLE
How i can Set an existing LiveConnectSession to the LiveConnectClient?

### ISSUE THREAD

**Issue by hatim-haffane** [liveservices/LiveSDK-for-iOS#29]
i'm trying to implement a multi connexion on my ios app so i can add two oneDrive account on my app , so i need to save the LiveConnectSession and set it to the current LiveConnectClient but the session property of the LiveConnectClient is readonly , so is there any way to do this?

**Comment by wangdxnum1** [comment]
I also have this problem.I hope LveSDK can support this feature
