### ISSUE TITLE
Unable to submit the iOS8 app to Apple by using Xcode 6 with OneDrive integration

### ISSUE THREAD

**Issue by logansiva** [liveservices/LiveSDK-for-iOS#40]
Hi,
      This is Loganathan from SignEasy. We have integrated the OneDrive SDK in our iOS app (https://itunes.apple.com/app/signeasy/id381786507?mt=8). With iOS8 and Xcode6.0, when we submit the app to Apple, Xcode's binary uploader shows an error as attached below.

![xcode6_submission_error](https://cloud.githubusercontent.com/assets/8103027/4358512/ef9c4da2-426a-11e4-90a1-74d639811e95.png)

OneDrive SDK integration guide mentions that we need to include the SDK framework in the copy bundle resource,  but Apple does not allow the submission of the app binary if we do so. If we don't add the OneDrive SDK framework in the copy bundle section, then SignEasy crashes when i try to initialize the library in our code.

Please let us know how we can fix this. I am reachable at loganathans@getsigneasy.com.

Thanks,
Sunil

**Comment by freecui** [comment]
I have solved this problem. I delete the file in the Copy Bundle Resources
