### ISSUE TITLE
logoutWithDelegate does not clear cookie?

### ISSUE THREAD

**Issue by fredrain** [liveservices/LiveSDK-for-iOS#46]
I try to use [liveClient logoutWithDelegate:self userState:@"logout"] to logout and clear last cookie, but afterwards I invoke [self.liveClient login:self scopes:scope delegate:self userState:@"signin"]; and LiveSDK does not show the user/password input page.

Is this a bug, or is there any other way to really logout as clearing cookies please kindly help to tell me, thanks.

**Comment by aclev** [comment]
I have not been able to reproduce this issue. Is it still happening? please reopen the issue if that is the case.

**Comment by wangdxnum1** [comment]
I call with scopes "wl.offline_access",this bug can be reproduced,but it did not happen 100%,I have see this bug several times.
