### ISSUE TITLE
64 bit support "_OBJC_CLASS_$_LiveConnectClient"

### ISSUE THREAD

**Issue by hatim-haffane** [liveservices/LiveSDK-for-iOS#57]
hello ,
when i try to build for 64bit i get this error  

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_LiveConnectClient", referenced from: objc-class-ref
 can you help me please

**Comment by aclev** [comment]
How are you referencing the project? Did you download the source directly or did you use cocoapods?
