### ISSUE TITLE
Can't use the sdk

### ISSUE THREAD

**Issue by francoC** [liveservices/LiveSDK-for-iOS#58]
Is this supposed to have a .framework file? I can't find it anywhere. I'm following the instructions of referencing the API source code directly, but it won't show me the login screen (it's just empty).

Regards,
F

**Comment by francoC** [comment]
FYI,

I put the "-fno-objc-arc" flag for the sdk classes so I can build them in my ARC project.

**Comment by rgregg** [comment]
@francoC we definitely recommend using the cocoapods approach to integrating the Live SDK to avoid that problem.
