### ISSUE TITLE
OneDrive for Business (preview)?

### ISSUE THREAD

**Issue by joshryan** [liveservices/LiveSDK-for-iOS#64]
Has any work been considered yet to implement OneDrive for Business support now that the OneDrive for Business (preview) is out?

https://dev.onedrive.com/odb-preview/release-notes.htm

**Comment by aclev** [comment]
HI @joshryan 
The LiveSDK is an SDK for the LiveConnect API and will not support the OneDrive for Business API.  However, we are working on an iOS SDK that will support the OneDrive for Business API.
Thanks,
Ace

**Comment by joshryan** [comment]
@aclev Cool. Do you have any potential time lines for and / or early glimpses at said OneDrive for Business SDK?

**Comment by aclev** [comment]
We don't have a time line yet.

**Comment by peternied** [comment]
@joshryan thanks for your enthusiasm!  We are working to provide clean, usable SDKs for these scenarios, stay tuned by watching https://github.com/OneDrive/onedrive-api-docs to see when we release updates to the service including SDKs

**Comment by rgregg** [comment]
We're aiming to deliver something by the end of June. You can also stay tuned to dev.onedrive.com to keep up to date with changes on the OneDrive API and SDKs.

**Comment by M13Kd** [comment]
Contact me ASAP


Sent from my MetroPCS 4G Android device

-------- Original message --------

**Comment by joshryan** [comment]
Thanks guys, I'll be watching.

**Comment by tobihagemann** [comment]
Any update on this?

Edit: Oh... just saw the switch to OneDrive SDK... does that include Business?

**Comment by aclev** [comment]
Right now the business portion is in preview, there will be full support for the OneDrive for Business APIs in the OneDrive SDK when the APIs are released themselves.
