### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by elihayc** [liveservices/LiveSDK-for-iOS#65]
Hi,
Please Create a new release (the last one is 4 mouthes ago)with the commit "Merge pull request #62 from aclev/fixMemoryIssues "
I'm using cocoapods, and the SDK crashed on the dealloc.

**Comment by aclev** [comment]
Hi @elihayc 
Thanks for noticing this! Everything is updated now.

**Comment by elihayc** [comment]
Thanks for the quick response.
