### ISSUE TITLE
Add user_id to LiveConnectSession object

### ISSUE THREAD

**Issue by aviramuse** [liveservices/LiveSDK-for-iOS#68]
The internal function [`readAuthResponse`](https://github.com/liveservices/LiveSDK-for-iOS/blob/master/src/LiveSDK/Library/Internal/Helpers/LiveAuthHelper.m#L177) has it, it just doesn't do anything with it, and we need it to identify different users.

**Comment by aclev** [comment]
Hi @aviramuse 
This is a good suggestion!  I will look into adding the property.  Feel free to submit a pull request with the changes as well.
Thanks for the input!

**Comment by avirambm** [comment]
Hi @aclev I am trying to push my branch with the modifications but I don't have enough permissions:
>ERROR: Permission to liveservices/LiveSDK-for-iOS.git denied to avirambm.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

Please advise.

**Comment by aclev** [comment]
Hi @avirambm 
You must submit a pull request for and changes you wish submit to the LiveSDK.  See [Pull Request Docs] (https://help.github.com/articles/using-pull-requests/) we use the fork & pull model.
Thanks
